### ISSUE TITLE
Exception during Emote loading [Unable to read beyond the end of the stream.]

### ISSUE THREAD

**Issue by Nanabell** [KazWolfe/XIVDeck#10]
Happens upon Game Startup. I assume when loading the icons for all configured emotes
Emote 20 is "Chuckle". The Button still works without any issues (and no further error logs) just thought I'd drop this here   

![image](https://user-images.githubusercontent.com/13600006/163805246-0e544033-5010-4a3f-9d9d-1d60ddf9c82d.png)

**Comment by KazWolfe** [comment]
Should be resolved with v0.1.5, maybe. Let me know if this problem continues past the update once it hits Dalamud Testing.

Thanks again for the report!
