### ISSUE TITLE
How to enable HQ icons?

### ISSUE THREAD

**Issue by BrakTap** [KazWolfe/XIVDeck#11]
In the dalamud log i can see the following message which leads me to ask if its possible to enble hq icons anywhere

[https://i.imgur.com/PsLblV3.png](url)

**Comment by KazWolfe** [comment]
Hi!

That field is specific to HQ items (that is, icons with the golden shine as seen below) and has no use for actions or similar. This will be automatically enabled where necessary.

![image](https://user-images.githubusercontent.com/5192145/164287445-25e4d56e-fbf2-4c91-aa38-19726a0686c9.png)

XIVDeck will automatically use high resolution icons where available (and if your system supports them).
