### ISSUE TITLE
TippyIPC error 

### ISSUE THREAD

**Issue by BrakTap** [KazWolfe/XIVDeck#17]
Hey i encountered this error resulting in a game crash, think you can take a look at it or if it's relateable to XIVdeck at all?

https://i.imgur.com/0bq3I5b.png
![0bq3I5b](https://user-images.githubusercontent.com/98245129/166110695-206ff2ce-9f5f-49f0-94ae-25bb6dc39b8b.png)

**Comment by KazWolfe** [comment]
Hi! Thanks for your report.

This exception is completely normal and will show up if you don't have Tippy installed in your game. Generally, this error won't even be visible unless you're in debug mode (or, apparently, post plugin logs to Franzbot). This error should not be related to your game crash.

I'll look into handling this error more gracefully though.
