### ISSUE TITLE
Target marking shortcuts do not work

### ISSUE THREAD

**Issue by BSoD38** [KazWolfe/XIVDeck#21]
Hi!

I started using XIVDeck a few weeks ago, and I mapped all target/enemy marking icons to my Stream Deck (with "Execute Action").

But the issue is that all markings that are "numbered" (attack 1-5, bind 1-3, do not attack 1-2) do not work. All other markings work though (square, circle, cross, triangle).

It seems that the plugin inputs a command with the full name of the marking, even though it doesn't exist :
![bug1](https://i.imgur.com/DjSYz3T.png)

The error says : `The first argument "mark" is incorrect (1st target to attack)`.

Manually inputting the command `/mk attack1` works perfectly.

For testing purposes, I tried inputting the command `/mk a` to see what the error message was :
![bug2](https://i.imgur.com/oxd4w0A.png)

`The first argument "mark" is incorrect (a)`

So it seems the plugin tries to run the command `/mk "1re cible à attaquer"`, but that marking name is non-existent.

Please note that my game language is set to French, and that might be the cause of the issue.

**Comment by KazWolfe** [comment]
Hi! Thank you for the report. I believe your analysis is correct and this is a localization issue caused by the French version of the game.

I'll take a look into this after maintenance and see what I can do to fix it in an upcoming release.

**Comment by KazWolfe** [comment]
Hiya! I managed to get to this a bit faster than I hoped.

A fix for this was pushed in version 0.2.3, which is currently available in [the testing repository](https://goatcorp.github.io/faq/dalamud_troubleshooting.html#q-how-do-i-enable-plugin-test-builds) for plugins. Assuming that nobody reports any issues to me for a little bit, I'll go ahead and push this out to all users later this week.

Thank you again for the report!
