### ISSUE TITLE
Uninstall plugin for Stream Deck

### ISSUE THREAD

**Issue by ghost** [KazWolfe/XIVDeck#22]
Hello!

Long story short, but I had to a system restore due to some issues w/ OneDrive. Now the plugin for stream deck isn't working properly, but it doesn't show up in the list of plugins. However If I try to "reinstall" it, Elgato says I can't because it's already there. 

After reading you're wiki post about building a plugin, do I just need to delete `%APPDATA%\Elgato\StreamDeck\Plugins\dev.wolf.xivdeck.sdPlugin` or is there anything else I should do? 

I'm not sure it's relevant, but for what it's worth, I did try disabling then reinstalling the plugin on Dalamud.

Thank you for your time, and especially all your work on this and Dalamud. 
[<a href="https://imgur.com/fnT24Sr"><img src="https://i.imgur.com/fnT24Sr.png" title="source: imgur.com" /></a>](url)

**Comment by KazWolfe** [comment]
Hiya! 

Yep, you should be okay to just manually delete that folder. Please ensure that you've fully closed the Stream Deck software first though, just to be on the safe side. 

You can also try to manually extract the plugin into the Plugins folder (just rename the `.streamDeckPlugin` to `.zip` and open), which may successfully repair the installation to the point where you'll be able to remove/reinstall the plugin properly.

If this doesn't work, I'd suggest reaching out to [Elgato Support](https://help.elgato.com/hc/en-us/requests/new) for additional guidance on manually uninstalling plugins.

I'll go ahead and close this ticket for now, but if you need further assistance, please feel free to reach out. Thanks!

**Comment by ghost** [comment]
Ok great. Thank you so much!
