### ISSUE TITLE
[Just a Thank you]

### ISSUE THREAD

**Issue by BrakusTapus** [KazWolfe/XIVDeck#23]
Heyo o/

If you were expecting a bug report I',m sorry to dissapoint you, I just wanted to thank you for the plugin been using it for a while now and it's great for switching between HuD lay-outs and different nameplate profiles. Also i like to comedic style of update notes, keep it up and thanks again!

**Comment by KazWolfe** [comment]
Hi there!

Thank you very much for your kind words, they mean a lot! I'm going to close this Issue just to keep my to-do list clean, but please don't hesitate to reach out if you have any issues with the plugin or want to suggest any improvements.

Thanks for sticking with me and this project!
