### ISSUE TITLE
StreamDeck app freezes when opening dropdown menus

### ISSUE THREAD

**Issue by capoferro** [KazWolfe/XIVDeck#25]
![image](https://user-images.githubusercontent.com/57349/178128794-f274e5f5-cc25-400c-9f37-6bf468cf61fc.png)

Whenever I open a dropdown menu to select an action or class or whatever, the Stream Deck app freezes. Are there logs somewhere I can upload that will help debug this?

I have the Dalamud plugin installed and the game is running.

**Comment by KazWolfe** [comment]
First things first: is your Stream Deck application on a second monitor? If so, can you please try moving it to your primary display and trying again? There's a known bug in the Elgato software that makes it perform oddly on secondary screens.

If the above does not solve the problem, can you please provide the following information?

* The version of the Stream Deck software you're running
* The operating system version you're running
* If this only happens with the Class dropdown

Thanks!

**Comment by capoferro** [comment]
Ah yep, that seems to be the problem. Using it on the primary monitor makes it much more reliable. Thanks for the info!
