### ISSUE TITLE
"Version out of date" nagging despite being up to date

### ISSUE THREAD

**Issue by MeidoDev** [KazWolfe/XIVDeck#29]
Ever since upgrading from 0.2.9 (which had been installed via Plugin Installer, not manually) to 0.2.10, I have been getting the "version is out of date" message upon every game start, despite being on the latest version.

Looks like the problem has persisted with 0.2.11

![image](https://user-images.githubusercontent.com/8738540/186510817-a729e1de-f7ac-42ef-bd04-eab4c991e210.png)

I have tried completely uninstalling the plugin and also deleting `XIVDeck.FFXIVPlugin.json`, so far to no avail.

**Comment by KazWolfe** [comment]
Hi! Can you please open the Stream Deck app, select any button, and send a copy/paste or a screenshot of the version diagnostics information at the bottom of the properties window? It should look like this:

![image](https://user-images.githubusercontent.com/5192145/186512204-06a51dec-3044-4e46-bfa4-cb36986b857b.png)

That error message pops up when the Stream Deck side of the plugin is out of date compared to the in-game version (as the Stream Deck side does not update automatically unfortunately). However, it's very possible I have a logic issue somewhere so I'd like to verify what version of the plugin you are running.

If the plugin versions _do_ mismatch, you can grab the latest (appropriate) version by clicking on the "version 0.2.12" text in the message. Do note, however, that I'll be publishing version 0.2.13 in the very near future, so it may make sense to wait for that to come out so you don't need to update twice.

**Comment by MeidoDev** [comment]
😅 
Right, for some reason I didn't realize that I should also update the plugin in the Stream Deck app (like the text tells me to).
Thanks for the enlightenment and sorry for the trouble!
