### ISSUE TITLE
When a hotbar is hidden the item icons don't load on the Streamdeck.

### ISSUE THREAD

**Issue by ShennyUK** [KazWolfe/XIVDeck#3]
Currently I have a bunch of food items on a hotbar I'd like to keep hidden on my UI, yet still have it accessible visually via the deck. 

Loading the game with a hidden hotbar displays as it does in the screenshot (no icon but still useable key). Unhiding and hidding the hotbar within the game returns the icon.

![image](https://user-images.githubusercontent.com/43541965/157037969-f2163d34-574c-41f4-b804-958fadb5f65b.png)

Edit: I guess this may fall into the Greyed Out Hotbar Slots aspect on your EAQ.

**Comment by KazWolfe** [comment]
Hiya, thanks for the report! Adding my own notes to this one so I can work on it later. This one definitely counts as a bug, the "greyed out" thing I was talking about was marking an action as unusable or similar.

#### Steps to Reproduce
1. Unhide a non-shared hotbar and populate it with random items.
2. Create Stream Deck icons pointing to that hotbar.
3. Hide the hotbar from view. *Note that icons will still remain present.*
4. Move icons around on other hotbars to trigger full refresh. *Note that icons will still remain present.*
5. Swap gearsets to a different class not using that non-shared hotbar.
6. Swap gearsets back to the original class used. ***Note that icons will not load, but the button will work.***
7. Unhide the hidden hotbar. *Icons will immediately reload.*
8. Re-hide the hidden hotbar. *Icons will not immediately unload and the game will remain in step 3-4 state.*

#### Initial Notes

I need to check but it's possible that the game doesn't load icons for hidden hotbars, which seems strange. I suspect this is going to be related to a similar bug I found where cross hotbar icons don't load if they're disabled/invisible.

I am very glad this isn't an edge case for just items or similar. Also note, this data does not appear to be provided by the game, so some clever workarounds may be necessary:

![image](https://user-images.githubusercontent.com/5192145/157081943-2f19f136-9ed6-4e34-9f4e-83444ab69fa7.png)

**Comment by KazWolfe** [comment]
This should now be fixed as of Release 0.0.4, which has been pushed to Dalamud Testing.

Please let me know if you still encounter this issue!
