### ISSUE TITLE
"Friend List" action can cause a crash

### ISSUE THREAD

**Issue by thlister** [KazWolfe/XIVDeck#31]
Steps to reproduce for me: 
- Add a new `Main Command` tile
- Set action to `[# 13] Friend List`
- Press button to use action in-game

**Expected**:
Friend List should open

**Actual**: 
Friend List opens most of the time. Game seems to crash 1/5 of the time. Repeatedly using the button to open and close the friend list seems to trigger it. 

**Notes**: 
- Latest plugin installed via Dalamud
- XIVDeck 0.2.14 Stream Deck plugin 
- Latest Stream Deck software

If there are any logs I could provide, let me know and I'll dig them up

**Comment by KazWolfe** [comment]
Hiya! Thank you for the bug report, I've been able to reproduce this on my end. That said, I do have some extra questions for you:

* Are there any `dalamud_appcrash` log files in your `%APPDATA%\XIVLauncher` folder correlating to the crash?
* When the crash happens, what exactly does the game do? Does the game freeze for a while, does it bring up a dialog box, does it just silently die, or something else?

Thanks!

**Comment by thlister** [comment]
[dalamud_appcrash_20220918_120531_260_4884.zip](https://github.com/KazWolfe/XIVDeck/files/9595749/dalamud_appcrash_20220918_120531_260_4884.zip)

Yay for reproducible! Try this log. When it happens, the game freezes for about two seconds, then fully dies with no error dialogs.

**Comment by KazWolfe** [comment]
Appears to be an upstream problem, should be resolved alongside https://github.com/goatcorp/Dalamud/pull/1015, but a new version of XIVDeck will likely be built as well.

**Comment by thlister** [comment]
Nice! I'll keep an eye out for updates all around. 

Thanks for looking into this and for all of your work. XIVDeck is awesome and has really brought me a lot of joy.

**Comment by KazWolfe** [comment]
The above PR was merged earlier today. With any luck, this should be resolved by one of the upcoming Dalamud updates.

Thanks again for the report!
