### ISSUE TITLE
Not an issue but a Thank you!

### ISSUE THREAD

**Issue by PetalTempest** [KazWolfe/XIVDeck#33]
Grats on 10k downloads! This is absolutely one of my **_must_** have plugins. I'd give you more stars if I could! Ty again!!!
[<a href="https://imgur.com/AS5rBfC"><img src="https://i.imgur.com/AS5rBfC.png" title="source: imgur.com" /></a>](url)

**Comment by KazWolfe** [comment]
Hiya! My apologies in getting back to you, things have been hectic 😅.

Thank you very much for your kind words; I'm very happy you're enjoying the plugin!
