### ISSUE TITLE
Emote motion only option

### ISSUE THREAD

**Issue by SnoFox** [KazWolfe/XIVDeck#34]
Would like to see an option for a motion-only emote; similar to executing something like `/backflip motion` from the chat box. I imagine this would simply look like a checkbox in the Stream Deck UI after Emote was picked as an action. 

Regardless if this is done or not, thank you so much for your work on this plugin!

**Comment by KazWolfe** [comment]
Hiya! Thank you for the feature request. This is absolutely something I have been working on in the background, but unfortunately I do not have an ETA for this feature just yet. 

Once I make some notable progress and release a testing version of this, I'll be sure to page you to let you know!

In the meantime, though, I would recommend you use the **Execute Command** feature to trigger your `/emote motion` command. Please note though that this will not automatically update the icon on your command button.

**Comment by KazWolfe** [comment]
This feature has landed in version 0.3.0, currently in testing!

![image](https://user-images.githubusercontent.com/5192145/209848651-2250c90f-8f29-40fc-bffc-bd228e3413f1.png)
