### ISSUE TITLE
Stream Deck Plugin Fails to Load After Update to 6.0.0

### ISSUE THREAD

**Issue by loveemetoinfinitybabe** [KazWolfe/XIVDeck#37]
After updating the Stream Deck software to version 6.0.0, the Stream Deck plugin failed to load, displaying the below for all my defined buttons:

![image](https://user-images.githubusercontent.com/118396593/202291398-39b478b7-93d8-4263-9f85-63654ec848a8.png)

Additionally, the XIVDeck category disappeared from the plugin sidebar, and I was not able to find any trace of the XIVDeck plugin being installed.

---

**Developer Note:** I have edited and hijacked this issue to be the authoritative reference for this particular problem. The below text of this issue is saved below for reference:

> I went to update the main file after i was prompted in game and I installed it only to find the entire plugin broken. It says its installed, but even the configure tab is gone in the streamdeck program alongside my actual buttons.

**Comment by KazWolfe** [comment]
Hi! I'm very sorry about this issue. So far, I'm still investigating this bug but it *seems* to be caused as a result of the update to Stream Deck Software 6.0.0. Unfortunately, I do not have a permanent fix for this particular problem at this time and I am waiting for additional information from Elgato to figure out how best to move forward.

Until I have a proper solution in place, please try to install [the latest version of the Stream Deck plugin](https://github.com/KazWolfe/XIVDeck/releases/latest) and see what happens. If this fails, please try a manual uninstall by following the below instructions:

1. Completely close the Stream Deck software by right-clicking the icon in your taskbar and selecting Quit.
2. Press the Windows and R keys to open the Run dialog, and type `%APPDATA%\Elgato\StreamDeck\Plugins`.
3. Delete the `dev.wolf.xivdeck.sdPlugin` folder.
4. Double-click the `.streamDeckPlugin` file downloaded above to open and install the Stream Deck Plugin.

I will continue investigating things on my end and possibly publish an update to include better messaging to fix this problem, if necessary.

**Comment by loveemetoinfinitybabe** [comment]
Thank you so much! Yeah for some reason it was not letting me find your folder the traditional way and once I installed the one you linked, it fixed itself!! :)

**Comment by KazWolfe** [comment]
Thank you for the confirmation. Did you need to manually uninstall the old version of the plugin before the Stream Deck app would work again?

Alternatively, I hope you don't mind, I'm going to edit your Issue and convert it to the authoritative one for this problem so I have somewhere to direct people 😅.

**Comment by loveemetoinfinitybabe** [comment]
Yeah I had to delete the folder completely so it didn’t recognize it and then reinstall for now! 

Also, that’s totally okay! I don’t mind at all!

**Comment by KazWolfe** [comment]
Resolving this, as it seems to have been fixed in 6.0.1. Anyone here in the future, please just reinstall the plugin.
