### ISSUE TITLE
Classes can get muddled

### ISSUE THREAD

**Issue by zbee** [KazWolfe/XIVDeck#5]
I am not certain how best to explain this, but the classes got muddled. It happened when I process-killed ffxiv, then re-opened with streamdeck still open, though I can't replicate.

This was the result:
![image](https://user-images.githubusercontent.com/1582821/158035107-fcad6da1-9484-4616-ab9e-89f4690fd042.png)

As you can see, DRK is selected, but it shows miner, and there's some duplication. It does actually still switch to the correct gearset though.

Disabling and re-enabling the plugin fixed it.

**Comment by KazWolfe** [comment]
This makes sense. What's happening is probably that the Stream Deck requested a list of classes again which got added to the existing list/selection.

I'll add this to the massive list of things to fix once I finally get around to rewriting the Stream Deck side in TypeScript. In the meantime, closing and reopening the Stream Deck app entirely (so right-click exit the icon in the Task Bar) should resolve this glitch as well.

Thanks for the report!

**Comment by KazWolfe** [comment]
This *should* be fixed as of version v0.1.0.

Thanks again for the report!
