### ISSUE TITLE
0.3.19 has no `.streamDeckPlugin` file

### ISSUE THREAD

**Issue by zbee** [KazWolfe/XIVDeck#51]
Previous releases have had a `.streamDeckPlugin` file attached, the instructions still say to download that file, and I don't see it in the source archives.

Is it missing? Or am I missing it?

**Comment by KazWolfe** [comment]
Ah, my CI broke. One second and I'll get that fixed.

**Comment by KazWolfe** [comment]
Fixed with 7abd9b60 for the future, but I also uploaded the artifact manually. All should be good now, thanks for the notice!
