### ISSUE TITLE
Also set /displayarms, /displayhead and /visor for selecting gearsets

### ISSUE THREAD

**Issue by SilentSwordmaiden** [KazWolfe/XIVDeck#52]
Hey,
I'd like to also select if weapons, helmets and visors are shown when applying a gearset with glam.

Maybe as a load for the api call where `true` means show, `false` means hide and not set just does the same as always?

```
message = {
    displayarms = true,
    displayhead = true,
    visor = true
}
```

**Comment by KazWolfe** [comment]
I don't think the game will allow you to do all of this as a single action, will it?

Assuming no, this would be out of scope for XIVDeck as it pushes the one-request-per-action rule. You can probably hack something together with a Macro, however.
