### ISSUE TITLE
Issue with /micon

### ISSUE THREAD

**Issue by SmashB101** [KazWolfe/XIVDeck#53]
When adding Macros, macro Icons set in the macro itself aren't displayed on the Stream Deck.

**Comment by KazWolfe** [comment]
Hi!

By default, XIVDeck doesn't render macro icons via `/micon` or similar for performance reasons. If you haven't already, please ensure you've enabled this setting via the Dalamud plugin's settings (open `/xlplugins`, find XIVDeck, and click the gear).

If you're still not seeing icons after enabling this setting, can you please reply with your macro so I can take a closer look?

Thanks!
