### ISSUE TITLE
Where is the .json link for Dalamud?

### ISSUE THREAD

**Issue by NM787** [KazWolfe/XIVDeck#55]
Hi, I'm sorry, I read your link before opening an issue. I still have no idea where to get help with this. Every other third party plugin i installed on Dalamud clearly stated what the .json link it was i needed to install. With yours, I couldn't find that link anywhere. I tried both https://github.com/KazWolfe/XIVDeck/blob/main/FFXIVPlugin/packages.lock.json as well as https://github.com/KazWolfe/XIVDeck/blob/main/global.json, and neither worked (I get the error message "download failed" for both...)

Could you please tell me what the correct .json link it is? Or is it perhaps just not updated for the current version of Dalamud and FFXIV?

Sorry about my noob question...

**Comment by zbee** [comment]
XIVDeck is not a third party plugin, and it is updated for the latest Dalamud.
You should be able to find it in your plugin installer: `/xlplugins` > "All Plugins" tab.

Here is similar info from the readme:
https://github.com/KazWolfe/XIVDeck/blob/7b4581d60ee53dc282e2a98bd0c30e72e3129e95/README.md?plain=1#L84-L86

And the latest accompanying streamdeck plugin is available in the latest release, hard-linked [here](https://github.com/KazWolfe/XIVDeck/releases/tag/v0.3.22).

**Comment by KazWolfe** [comment]
As zbee said, this project is an official Dalamud plugin, so it's included in the main Dalamud repository. You don't need to take any extra steps to install this plugin beyond manually downloading the Stream Deck plugin artifact.

If you continue to have problems, please don't hesitate to reach out and I'll see what I can do.
