### ISSUE TITLE
[BUG] General Action Limit Break activates Sprint and not LB

### ISSUE THREAD

**Issue by ShennyUK** [KazWolfe/XIVDeck#7]
Using the General Action Limit Break button enables sprint. I checked to see if they were reversed or something but Sprint is Sprint but LB button is still activating sprint even when creating a new button/action.

**Comment by KazWolfe** [comment]
Hi and thanks for your report! I'm unfortunately unable to reproduce this bug. Can you please grab the following things for me:

1. The version data from your Stream Deck plugin. There should be two barely-visible lines under the `Port` field. You may either copy and paste these lines or simply take a screenshot.
![image](https://user-images.githubusercontent.com/5192145/161196515-9bcf3b61-7dc9-4b77-bbbf-ef21599a731e.png)
2. A debug plugin log of you pressing both a Sprint and Limit Break button. This should be at least two lines, both in format `Got HTTP request POST /action/GeneralAction/##`

Additionally, can you please provide a full list of installed plugins in your game? If you have any issues getting this information or would just rather get it to me over Discord, that's totally fine!

**Comment by KazWolfe** [comment]
Resolved over Discord - issue caused by third-party plugin.
